spring:
  datasource:
    url: jdbc:sqlserver://beatbridge.database.windows.net:1433;database=BeatBridgeDb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: adicom02
    password: AdrianBP1#
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080

  